MOUSE_BUTTON_LEFT         = 0
MOUSE_BUTTON_RIGHT        = 1
MOUSE_BUTTON_LEFT_UP      = 2
MOUSE_BUTTON_LEFT_DOWN    = 3
MOUSE_BUTTON_RIGHT_UP     = 4
MOUSE_BUTTON_RIGHT_DOWN   = 5
MOUSE_BUTTON_INVALID      = -1

KEY_DIRECTION_RIGHT       = 0
KEY_DIRECTION_UP          = 1
KEY_DIRECTION_DOWN        = 2
KEY_DIRECTION_LEFT        = 3
KEY_DIRECTION_INVALID     = -1

MOUSE_POSITION_INVALID    = -1
